### ISSUE TITLE
I'm not able to make slickAdd working

### ISSUE THREAD

**Issue by giggioz** [udondan/meteor-slick#3]
Hi!

I'm just trying a simple slickAdd

My slick is rendered fine

```
Template.avatar.rendered = function() {

    $('#avatar').slick({
      dots: false,
      arrows: true
    });
};
```

Somewhere else after a button click i do

```
$('#avatar').slick('slickAdd','<div><img src="/N03.png"></div>');
```

But it does not add anything to my list, i inspected the dom and the dom is unaffected..

any idea?

Thanks.

**Comment by Dsyko** [comment]
Hey, I just ran into this same issue, this package uses an older version of slick, which has a different API for adding elements. For this version you need to use

 `$('#avatar').slickAdd('<div><img src="/N03.png"></div>');`

**Comment by udondan** [comment]
Please try https://github.com/timbrandin/meteor-slick - Unfortunately I'm currently not working with Meteor at all.
