### ISSUE TITLE
This package is not up to date

### ISSUE THREAD

**Issue by mquandalle** [udondan/meteor-slick#4]
Latest version of slick is v1.5.3.

**Comment by timbrandin** [comment]
https://github.com/timbrandin/meteor-slick (1.5.8)

**Comment by paulgnz** [comment]
Awesome thanks @timbrandin

**Comment by skattwood** [comment]
@timbrandin how do I link the meteor package to your fork?

**Comment by timbrandin** [comment]
@skattwood you could use timbrandin:slick for the time being :)

**Comment by skattwood** [comment]
Ah I see. I was confused because your documentation still had the `meteor add udondan:slick` command to install. Thanks!

**Comment by timbrandin** [comment]
Oh, gonna fix that. // T

2015-12-21 18:05 GMT+01:00 Scott Attwood <notifications@github.com>:

> Ah I see. I was confused because your documentation still had the meteor
> add udondan:slick command to install. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/udondan/meteor-slick/issues/4#issuecomment-166360639>.
>



-- 
Cheers,
// Tim Brandin @timbrandin <https://twitter.com/#!/timbrandin>
http://timbrandin.com
http://studiointeract.com
