### ISSUE TITLE
Events not firing!

### ISSUE THREAD

**Issue by Roshdy** [udondan/meteor-slick#6]
I'm unable to catch any event for the slick object at all

I tried:-
* Object binding (onRendered)
```
slickObj = $('.my-slick').slick({
	infinite: false,
	dots: false,
	accessibility: false,
	arrows: true,
	mobileFirst: true,
	swipe: true
});
slickObj.on('beforeChange', function(e, slick, currentSlide, nextSlide){
	console.log(currentSlide, nextSlide);
});
```
* jQuery binding (onRendered)
```
slickObj = $('.my-slick').slick({
	infinite: false,
	dots: false,
	accessibility: false,
	arrows: true,
	mobileFirst: true,
	swipe: true
}).on('beforeChange', function(e, slick, currentSlide, nextSlide){
	console.log(currentSlide, nextSlide);
});
```
* Template events
```
'beforeChange .my-slick': function(event, t, slick, currentSlide, nextSlide){
	console.log(currentSlide, nextSlide);
}
```

Please advise!

**Comment by udondan** [comment]
Sorry Roshdy, this is 3 years old and very likely to no longer work with Meteor. After all Meteor was a big disappointment for me - things permanently stopped working due to changes on Meteor, the packaging system etc. I no longer work with it since at least two years.
